---
output:
  officedown::rdocx_document:
    reference_docx: style_template.docx
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "../outputs/",
      envir = globalenv()
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, echo = FALSE)

library(here)

source(paste0(here(),"/code/config.R"))
source(paste0(here(),"/code/data_prep.R"))

```

<!---BLOCK_MULTICOL_START--->

::: {custom-style="heading_style"}
STATISTICS PRESS NOTICE
:::

`r run_columnbreak()` `r external_img(paste0(here(),"/data/images/NISRA_logo_bilingual_colour.png"), height = 2.22, width = 5, unit = "cm")`

<!---BLOCK_MULTICOL_STOP{widths: [2, 5], space: 0.2, sep: false}--->

::: {custom-style="heading_style"}
`r run_columnbreak()` Public Awareness of and Trust in Official Statistics, Northern Ireland `r current_year`
:::

The level of public trust in official statistics produced by the Northern Ireland Statistics and 
Research Agency (NISRA), the government agency which produces the majority of Northern 
Ireland official statistics across all government departments remains high. \
\
This is according to the latest findings from the ‘Public Awareness of and Trust in Northern 
Ireland Official Statistics’ questions in the Northern Ireland Continuous Household Survey.\
\
The report shows the majority of respondents (`r trust_in_nisra_stats`%), surveyed in September to December 
2022, trust NISRA statistics a great deal or tend to trust them. The level of trust in NISRA 
statistics increases to (`r heard_of_and_trust_in_nisra_stats`%) for those respondents who have heard of NISRA by name.\
\
Trust in NISRA as the body which produces official statistics is also high, with (`r trust_in_nisra`%) of 
respondents trusting NISRA a great deal or tending to trust NISRA; this remains higher than 
in 2019 (80%), prior to the onset of the COVID-19 pandemic. Trust in NISRA is also higher 
than trust in the Civil Service (`r trust_in_nics`%) and compares favourably with trust in the media (`r trust_in_media`%) 
and the NI Assembly (`r trust_in_assembly`%).\
\
Other key findings are as follows:

**Awareness** \

1. Almost half of respondents (`r heard_of_nisra`%) indicated they had heard of NISRA before being
contacted about the survey. \

**Value** \

2. Statistics produced by NISRA are valued - 9 out of 10 respondents (`r importance_of_stats`%) agree that
statistics produced by NISRA are important to understand Northern Ireland.

**Political Interference**

3. Over four-fifths (`r free_from_interference`%) of respondents believe that statistics produced by NISRA are free
from political interference. \

\newpage

::: {custom-style="heading_style"}
**NOTES TO EDITORS**
:::

1. The ‘Public Awareness of and Trust in Official Statistics, Northern Ireland `r current_year`’ 
publication, data tables and accompanying infographics can be found at:
\
https://www.nisra.gov.uk/publications/public-awareness-and-trust-official-statistics-2022
\
2. The questions were asked in the Northern Ireland Continuous Household Survey (CHS) 
between September and December `r current_year`. The percentages reported are based on a 
representative sample of the population (`r sample_size` persons) and are therefore estimates.
\
3. NISRA is an Agency within the Department of Finance and provides statistical services 
across government in Northern Ireland. The majority of Northern Ireland official statistics 
are produced by NISRA staff. NISRA branches can be found within all Northern Ireland 
Departments and many Arm’s Length Bodies.
\
4. NISRA produces official statistics for Northern Ireland on a wide range of issues, including 
births, deaths and marriages; the size of the population of Northern Ireland; qualifications 
of school leavers; recorded levels of crime; hospital waiting times; people living in poverty; 
the NI Census; journeys made by walking, cycling or public transport; and the 
unemployment rate.
\
5. Official statistics are statistical outputs produced by Government departments and 
agencies, the Office for National Statistics, and by other Crown bodies. Official statistics 
are fundamental to good government, to the delivery of public services and to decisionmaking in all sectors of society. National Statistics are a subset of official statistics.
\
6. The Code of Practice for Statistics, produced by the Office for Statistics Regulation (OSR),
outlines the principles and detailed practices that producers of official statistics must 
commit to when producing and releasing official statistics. It is based on three pillars:
\
• **Trustworthiness** is about having confidence in the people and organisations that 
produce statistics and data.
• **Quality** is about using data and methods that produce assured statistics.
• **Value** is about producing statistics that support society’s needs for information.
\
7. Further information on the statistics provided in this publication can be obtained from 
NISRA Statistical Support Branch. \
Lead Statistician: Norma Broomfield, Statistical Support Branch, NISRA \
Norma.Broomfield@nisra.gov.uk Tel: 028 9038 8481
\
8. For media queries, please contact the DoF Press Office at dof.pressoffice@financeni.gov.uk or on Tel: 028 90816724. The Executive Information Service operates an out of 
hours service **for media enquiries only** between 1800hrs and 0800hrs Monday to Friday 
and at weekends and public holidays. The duty press officer can be contacted on 028 
9037 8110.
\
9. Follow NISRA on Twitter, Facebook and YouTube


