---
title: "07 Notes for Readers Sub  Report"
output: html_document
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "../demo/demo_outputs/",
      output_file = paste0(
        xfun::sans_ext(input), '_', format(Sys.time(), "%d-%m-%Y_%H%M") , '.html'
      ),
      envir = globalenv()
    )
  })
---
  
  

```{r, include=FALSE}
# this chunk sets chunk options for all chunks in this file
knitr::opts_chunk$set(
  message = FALSE, echo = FALSE
)

library(here)

source(paste0(here(), "/code/config.R"))
source(paste0(here(), "/code/demo/demo_data_prep.R"))
source(paste0(here(), "/code/demo/demo_config.R"))
```

This section has been separated from the main section of the document to aid navigation. Normally a publication should contain a separate section of this nature and can be named ‘Notes for Readers', ‘Background Notes’ or ‘Supporting Information’. It should include:

  - definitions (or a link to definitions) of all relevant concepts and terms. Whether the definition is included in the text, the Notes section or a link provided depends on the importance of the reader knowing the correct definition
  - key quality information (including any limitations or key caveats) and a link to the Background Quality Report (or the equivalent). Where appropriate, limitations or caveats should also be flagged in the text alongside the data, as not all users will read the Notes section
  - links to the equivalent statistics in England, Scotland and Wales (and if appropriate RoI) or indicate that equivalent statistics are not available (with an explanation or guidance on comparison if appropriate) - assuming this information is not included elsewhere in the publication

It may include (if relevant):

  - a series of methodology notes (or a link to the methodology used to produce the statistics). This may include details of the data sources used to produce the statistics.
  - information on how the statistics are used, for example if they are used to measure key performance targets; and advice on the appropriate use of the statistics
  - links to related statistics, including where appropriate guidance on the coherence and comparability of the statistics 
  - links to social media accounts [Twitter](https://twitter.com/NISRA) and [Facebook](https://www.facebook.com/nisra.gov.uk)
  - information on supplementary statistical services
  - date of the next release
  - links to [previous publications](https://www.nisra.gov.uk/publications/2021-mid-year-population-estimates-northern-ireland)
  - email addresses should all be lowercase jo.bloggs@nisra.gov.uk and it is good practice to include a named individual (some exemptions apply)
  - links to downloads should have file type and size in the link text [2022 Mid-year population estimates statistical bulletin pdf 545KB](https://www.nisra.gov.uk/system/files/statistics/Statistical%20Bulletin%20-%202022%20Mid-year%20Population%20Estimates%20for%20Northern%20Ireland.pdf)

With regards to adding 'Contact Details', they may be included in this section. However the RAP skeleton has a contact details function called `f_contact` in the `html_formatting` R script within the functions folder. This function is called at the bottom of a report (Section 13) above the footer and is the recommended way to add contact details to a report as it ensures consistency for users. Information for specific contact details can be added and edited in the config file.
