---
title: "Public Awareness Of And Trust In Official Statistics, Northern Ireland 2022"
lang: "en"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_download: no
    css: "../style.css"
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "../../outputs/",
      envir = globalenv()
    )
  })
---

<div id = "cookie-banner"></div>
<script src = "../cookies.js"></script>

```{r settings, include=FALSE}
# this chunk sets chunk options for all chunks in this file
knitr::opts_chunk$set(
  message = FALSE, echo = FALSE, warning = FALSE, out.width = "100%", fig.height = 4
)

library(here)
source(paste0(here(), "/code/ods_tables/run_ods_tables.R"))
```


```{css}
h3 {
  color: black;
  font-weight: bold;
}
```

<div data-nics-theme="`r nics_theme`">

`r f_banner(title = rmarkdown::metadata$title, subtitle = "Appendix B: Detailed Tables")` 

<div id="main" role="main">

[Back to full report](public-awareness-of-and-trust-in-official-statistics-northern-ireland-`r current_year`.html)

## Appendix B: Detailed Tables

Detailed tables including the source data for all the charts and commentary and additional breakdowns are published alongside this report.

`r embed_file(ods_filename, text = "Download all tables")` (.ODS format; `r ods_filesize`)

### Awareness of the Northern Ireland Statistics and Research Agency (NISRA)

 * `r f_embed_ods(df = table_1a_data, sheet_title = paste0("Table 1a: Awareness of NISRA, 2009 to ", current_year), tab_name = "awareness_of_nisra", app_b = TRUE)`
 * `r f_embed_ods(df = table_1b_data, sheet_title = if (current_year == ons_year) {paste0("Table 1b: Awareness of NISRA and ONS, ", current_year)} else {paste0("Table 1b: Awareness of NISRA (", current_year, ") and ONS (", ons_year, ")")}, tab_name = "awareness_of_nisra_and_ons", app_b = TRUE)`
 * `r f_embed_ods(df = table_1c_data, sheet_title = paste0("Table 1c: Awareness of ONS, 2014 to ", ons_year), tab_name = "awareness_of_ons", app_b = TRUE)`

### Awareness of NISRA statistics among those who had not previously heard of NISRA

* `r f_embed_ods(df = table_2.1a_data, sheet_title = paste0("Table 2.1a: Aware of NISRA statistics on the number of deaths in Northern Ireland, ", current_year), tab_name = "aware_death_statistics", app_b = TRUE)`
* `r f_embed_ods(df = table_2.1b_data, sheet_title = paste0("Table 2.1b: Aware of NISRA statistics on recorded levels of crime in Northern Ireland, ", current_year), tab_name = "aware_crime_statistics", app_b = TRUE)`
* `r f_embed_ods(df = table_2.1c_data, sheet_title = paste0("Table 2.1c: Aware of NISRA statistics on the qualifications of school leavers in Northern Ireland, ", current_year), tab_name = "aware_school_leavers", app_b = TRUE)`
* `r f_embed_ods(df = table_2.1d_data, sheet_title = paste0("Table 2.1d: Aware of NISRA statistics on the number of people who live in Northern Ireland, ", current_year), tab_name = "aware_num_people", app_b = TRUE)`
* `r f_embed_ods(df = table_2.1e_data, sheet_title = paste0("Table 2.1e: Aware of NISRA statistics on hospital waiting times in Northern Ireland, ", current_year), tab_name = "aware_hospital", app_b = TRUE)`
* `r f_embed_ods(df = table_2.1f_data, sheet_title = paste0("Table 2.1f: Aware of NISRA statistics on the Northern Ireland Census every ten years, ", current_year), tab_name = "aware_census", app_b = TRUE)`
* `r f_embed_ods(df = table_2.1g_data, sheet_title = paste0("Table 2.1g: Aware of NISRA statistics on the unemployment rate in Northern Ireland, ", current_year), tab_name = "aware_unemploy", app_b = TRUE)`
* `r f_embed_ods(df = table_2.1h_data, sheet_title = paste0("Table 2.1h: Aware of NISRA statistics on people living in poverty in Northern Ireland, ", current_year), tab_name = "aware_poverty", app_b = TRUE)`
* `r f_embed_ods(df = table_2.1i_data, sheet_title = paste0("Table 2.1i: Aware of NISRA statistics on percentage of journeys made by walking, cycling or public transport in Northern Ireland, ", current_year), tab_name = "aware_transport", app_b = TRUE)`
* `r f_embed_ods(df = table_2.1j_data, sheet_title = paste0("Table 2.1j: Number of selected NISRA statistics respondents had heard of (among those who were not previously aware of NISRA), ", current_year), tab_name = "aware_num_stats", app_b = TRUE)`

### Awareness that specified statistics are produced by NISRA statisticians among those who were aware of NISRA

* `r f_embed_ods(df = table_2.2a_data, sheet_title = paste0("Table 2.2a: Aware that statistics on the number of deaths in Northern Ireland are produced by NISRA statisticians, ", current_year), tab_name = "aware_death_by_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_2.2b_data, sheet_title = paste0("Table 2.2b: Aware that statistics on recorded levels of crime in Northern Ireland are produced by NISRA statisticians, ", current_year), tab_name = "aware_crime_by_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_2.2c_data, sheet_title = paste0("Table 2.2c: Aware that statistics on the qualifications of school leavers in Northern Ireland are produced by NISRA statisticians, ", current_year), tab_name = "aware_qualifications_by_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_2.2d_data, sheet_title = paste0("Table 2.2d: Aware that statistics on the number of people who live in Northern Ireland are produced by NISRA statisticians, ", current_year), tab_name = "aware_people_by_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_2.2e_data, sheet_title = paste0("Table 2.2e: Aware that statistics on hospital waiting times in Northern Ireland are produced by NISRA statisticians, ", current_year), tab_name = "aware_hospital_by_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_2.2f_data, sheet_title = paste0("Table 2.2f: Aware that statistics on the Northern Ireland Census every ten years are produced by NISRA statisticians, ", current_year), tab_name = "aware_census_by_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_2.2g_data, sheet_title = paste0("Table 2.2g: Aware that statistics on the unemployment rate in Northern Ireland are produced by NISRA statisticians, ", current_year), tab_name = "aware_unemployment_by_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_2.2h_data, sheet_title = paste0("Table 2.2h: Aware that statistics on people living in poverty in Northern Ireland are produced by NISRA statisticians, ", current_year), tab_name = "aware_poverty_by_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_2.2i_data, sheet_title = paste0("Table 2.2i: Aware that statistics on the percentage of journeys made by walking, cycling or public transport in Northern Ireland are produced by NISRA statisticians, ", current_year), tab_name = "aware_walking_by_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_2.2j_data, sheet_title = paste0("Table 2.2j: Number of specified statistics respondents are aware are produced by NISRA statisticians (among those who had previously heard of NISRA), ", current_year), tab_name = "aware_num_stats_by_nisra", app_b = TRUE)`


### Trust in NISRA

* `r f_embed_ods(df = table_3.1a_data, sheet_title = paste0("Table 3.1a: Trust in NISRA, 2014 to ", current_year), tab_name = "trust_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_3.1b_data, sheet_title = if (current_year == ons_year) {paste0("Table 3.1b: Trust in NISRA and ONS, ", current_year)} else {paste0("Table 3.1b: Trust in NISRA (", current_year, ") and ONS (", ons_year, ")")}, tab_name = "trust_nisra_ons", app_b = TRUE)`
* `r f_embed_ods(df = table_3.1c_data, sheet_title = paste0("Table 3.1c: Trust in NISRA by respondent’s awareness of NISRA, ", current_year), tab_name = "trust_nisra_awareness", app_b = TRUE)`

### Trust in the Civil Service

* `r f_embed_ods(df = table_3.2a_data, sheet_title = paste0("Table 3.2a: Trust in the Civil Service, 2014 to ", current_year), tab_name = "trust_nics", app_b = TRUE)`

### Trust in the Northern Ireland Assembly

* `r f_embed_ods(df = table_3.3a_data, sheet_title = paste0("Table 3.3a: Trust in the Northern Ireland Assembly, 2014 to ", current_year), tab_name = "trust_assembly", app_b = TRUE)`

### Trust in the Media

* `r f_embed_ods(df = table_3.4a_data, sheet_title = paste0("Table 3.4a: Trust in the Media, 2014 to ", current_year), tab_name = "trust_media", app_b = TRUE)`

### Trust in the statistics produced by NISRA

* `r f_embed_ods(df = table_4a_data, sheet_title = paste0("Table 4a: Trust in NISRA statistics, 2014 to ", current_year), tab_name = "trust_stats", app_b = TRUE)`
* `r f_embed_ods(df = table_4b_data, sheet_title = if (current_year == ons_year) {paste0("Table 4b: Trust in NISRA statistics and ONS statistics, ", current_year, ")")} else {paste0("Table 4b: Trust in NISRA statistics (", current_year, ") and ONS statistics (", ons_year, ")")}, tab_name ="trust_nisra_ons_stats", app_b = TRUE)`
* `r f_embed_ods(df = table_4c_data, sheet_title = paste0("Table 4c: Trust in NISRA statistics by respondent’s awareness of NISRA, ", current_year), tab_name = "trust_stats_awareness", app_b = TRUE)`
* `r f_embed_ods(df = table_4d_data, sheet_title = paste0("Table 4d: Trust in ONS statistics, 2014 to ", ons_year), tab_name = "trust_ons_stats", app_b = TRUE)`

### Value

* `r f_embed_ods(df = table_5a_data, sheet_title = paste0("Table 5a: Statistics produced by NISRA are important to understand Northern Ireland, 2016 to ", current_year), tab_name = "value_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_5b_data, sheet_title = if (current_year == ons_year) {paste0("Table 5b: Statistics produced are important to understand our country (NISRA and ONS), ", current_year)} else { paste0("Table 5b: Statistics produced are important to understand our country (NISRA ", current_year, " and ONS ", ons_year, ")")}, tab_name = "trust_nisra_ons_stats", app_b = TRUE)`
* `r f_embed_ods(df = table_5c_data, sheet_title = paste0("Table 5c: Statistics produced by NISRA are important to understand Northern Ireland, by whether or not the respondent had heard of NISRA, ", current_year), tab_name = "trust_stats_awareness", app_b = TRUE)`

### Political Interference

* `r f_embed_ods(df = table_6a_data, sheet_title = paste0("Table 6a: Statistics produced by NISRA are free from political interference, 2014 to ", current_year), tab_name = "political_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_6b_data, sheet_title = if (current_year == ons_year) {paste0("Table 6b: Statistics produced are free from political interference (NISRA and ONS) , ", current_year)} else {paste0("Table 6b: Statistics produced are free from political interference (NISRA ", current_year, " and ONS ", ons_year, ")")}, tab_name = "political_nisra_ons", app_b = TRUE)`

### Confidentiality

* `r f_embed_ods(df = table_7a_data, sheet_title = paste0("Table 7a: Personal information provided to NISRA will be kept confidential, 2014 to ", current_year), tab_name = "confidential_nisra", app_b = TRUE)`
* `r f_embed_ods(df = table_7b_data, sheet_title = if (current_year == ons_year) {paste0("Table 7b: Personal information provided will be kept confidential (NISRA and ONS), ", current_year)} else {paste0("Table 7b: Personal information provided will be kept confidential (NISRA ", current_year, " and ONS ", ons_year, ")")}, tab_name = "confidential_nisra_ons", app_b = TRUE)`

<!-- closing main div -->
</div>

`r f_footer()`

<!-- message to rotate screen if it is below 400px width -->
<div id="rotate-screen">
  <p style="color: white;">Please rotate your screen for optimal experience</p>
</div>


```{js}

// Function to remove map shapes from tab order, and add tabs to table of contents

function tabOrder() {
  
  // Make side menu tabbable

  let headings = document.getElementsByClassName('tocify-item list-group-item');
  
  for (let i = 0; i < headings.length; i ++) {
    headings[i].innerHTML = "<a href='#" + headings[i].getAttribute("data-unique") + "'>" + headings[i].innerHTML +  "</a>";
  }
  
};

// Instruct web browser to run above function when loaded
window.onload = tabOrder;
```


<!-- close data-nics-theme div-->
</div>
